plugins:
  nexudus_auth_enabled:
    default: true
    type: bool
    client: true
  nexudus_auth_group:
    default: "makerspace-members"
    type: string
  nexudus_auth_diagnostics:
    default: false
    type: bool
